{% set version = "0.4.0" %}

package:
  name: sqlparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sqlparse/sqlparse-{{ version }}.tar.gz
  sha256: d59e473424ae7470778fa4dd0dd7bb666ff324f0a6106c29deb5946ea5367f04

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - sqlformat = sqlparse.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sqlparse

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.org
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
