{% set version = "0.4.4" %}

package:
  name: sqlparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sqlparse/sqlparse-{{ version }}.tar.gz
  sha256: d446183e84b8349fa3061f0fe7f06ca94ba65b426946ffebe6e3e8295332420c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sqlformat = sqlparse.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sqlparse

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.org
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
