travis:
  secure:
    BINSTAR_TOKEN: LCweKZ1xRgVDZjT1VEYNDdhsxma/A67Emy9h82IJRz/h2y4kVa4b6Ku7O6aVg2UO7R0TvZAJ5IJDNiMEKF0PibLuLoOAqyKJgbWcKaoGEeld93q86lp3L5M0Lc0WC1JJzvfKDx2HQeNcqFSucm8zrD2raIMHV0xHdgL12P+shm3Ybdn6UB2QCOapWsld4F3IgegpVf6VJm3fNY6N2SLzZFHQ2tGRSLtFh9MAc8goLWQP2T4UtogItQ/M7YfYw/SoK1HfH9XfQ2pfsXSkhA9pXqUkUgcErsPbG3kDLvCpjAFbdqyfN85UKxHYrbGvq3VmoxrpN2xKJk71M82Af/g/KY0SpRfzt/fgEVFcrLAz7jyxtzXRTyKQ+VI9DNdAEm+uNJN9NiuQQiaU3aNdyUXlMMg9TTbkf7O9zfofhd2NV4Uvdw9paDHJaSq1/6rKQ266ov5wCRqqghPQ1g6aHor+EPmQz+ihnlQ1Ie4FiVw4xYIG6VV76jtgAmmNGhaB9xvzbh8fXodL3bGUJC/Tx3fgtLmRHKpS+iH5HtiDNsoF0+YqEFZuUpEpBIPBDplTI3JlBryJUqk8CKMsXtVBAmxZyZu9WrNEHOMkZy1t3NbzDjO0TgNnGc7SOg+rIVAuyUVibPDa+Kv9GDA0zMuzZF8wBsu7NqoiWK5gnaH8ymbFmII=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
